In [1]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [2]:
random = np.random.random((3,3,3))
random

array([[[0.73049802, 0.05289206, 0.0526833 ],
        [0.20400888, 0.47778946, 0.70258453],
        [0.05749045, 0.41524484, 0.12404035]],

       [[0.51485958, 0.57313044, 0.31606634],
        [0.89566415, 0.28911208, 0.25136947],
        [0.41051669, 0.90625973, 0.60772908]],

       [[0.75195558, 0.28610963, 0.25489573],
        [0.39469243, 0.10453355, 0.4662969 ],
        [0.68721965, 0.21508423, 0.80348543]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
a = np.zeros((5,5),dtype=int)
a[4,:4] = [1,2,3,4]
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 2, 3, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
x = np.zeros((8,8),dtype=int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [19]:
x = np.random.random((5,5))
print('Before Normalize ======= \n')
print(x)
norm = np.linalg.norm(x)
normal_array = x/norm
print('\nAfter normalize ======= \n')
normal_array

Before Normalize ======= 

[[0.66562461 0.32957136 0.36165062 0.526111   0.42472996]
 [0.81978073 0.57128475 0.88111074 0.80060352 0.34992523]
 [0.77273869 0.89649666 0.78573034 0.28340737 0.88190845]
 [0.54538261 0.82802212 0.23369201 0.20287765 0.95833623]
 [0.76615276 0.18825085 0.46938131 0.50253021 0.1723629 ]]

After normalize ======= 



array([[0.21398019, 0.10594822, 0.11626083, 0.16913037, 0.13653912],
       [0.26353719, 0.1836525 , 0.28325312, 0.25737224, 0.11249144],
       [0.24841445, 0.28819927, 0.25259092, 0.09110776, 0.28350956],
       [0.17532566, 0.26618657, 0.07512562, 0.06521964, 0.30807901],
       [0.24629726, 0.06051752, 0.15089331, 0.16154978, 0.05540998]])

# 5.  How to find common values between two arrays?

In [6]:
a1 = [1,2,4,5]
a2 = [1,4,6,7]
intersect = np.intersect1d(a1, a2)
intersect

array([1, 4])

# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
import datetime as dt

today = dt.date.today()
yest = today -  dt.timedelta(days= 1)
tomw = today +  dt.timedelta(days= 1)

print('today', today)
print('yesterday', yest)
print('tomorrow', tomw)

today 2020-07-26
yesterday 2020-07-25
tomorrow 2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [8]:
comp = np.random.randint(1,6, size=(5)) == np.random.randint(1,6, size=(5))
comp.all()

False

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
arr = np.random.randint(3, 100, (10))
print(arr)
maxindex = np.argmax(arr)

arr[maxindex] = 0
print('after change max val = 0')
print(arr)


[23 17 32 64 37 58 37 26 75 31]
after change max val = 0
[23 17 32 64 37 58 37 26  0 31]


# 9. How to print all the values of an array?

In [10]:
arr = np.random.randint(3, 100, (10))
print(*arr)

65 53 68 80 28 8 64 51 3 5


# 10.Subtract the mean of each row of a matrix

In [11]:
print("Original matrix:\n")
np.random.seed(3)
X = np.random.randint(3, 10, (4,4))
print(X)
mean =X.mean(axis=1)
print(mean)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - mean
print(Y)

Original matrix:

[[5 3 4 6]
 [3 3 3 8]
 [8 6 5 6]
 [4 4 5 8]]
[4.5  4.25 6.25 5.25]

Subtract the mean of each row of the said matrix:

[[ 0.5  -1.25 -2.25  0.75]
 [-1.5  -1.25 -3.25  2.75]
 [ 3.5   1.75 -1.25  0.75]
 [-0.5  -0.25 -1.25  2.75]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [12]:
vector1 = np.array([32,22,13,24,15,16])
index_vector = np.array([3,1,2,0,1,2])

result = np.take_along_axis(vector1, index_vector, axis=0)+1
result

array([25, 23, 14, 33, 23, 14])

# 12.How to get the diagonal of a dot product?

In [13]:
vector_a = np.random.randint(3, 10, (4,4))
vector_b = np.random.randint(3, 10, (4,4))

product = np.dot(vector_a, vector_b) 
print(product)
diag = np.diag(product)

diag

[[127 201  84 188]
 [114 193  93 157]
 [114 183  79 145]
 [101 168  80 138]]


array([127, 193,  79, 138])

# 13.How to find the most frequent value in an array?

In [14]:
from scipy import stats

arr = np.array([1,1,1,2,3,4,1,3,4,2,3])
stats.mode(arr)[0]

array([1])

# 14.How to get the n largest values of an array

In [15]:
arr = np.random.randint(3, 100, (10))
print('array')
print(arr)
n = 3
nlargest = arr[(-arr).argsort()[:n]]
print('n-largest')
print(nlargest)

array
[23 97 52 24 81 31 57  3 67 21]
n-largest
[97 81 67]


# 15.How to create a record array from a regular array?

In [16]:
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])

result= np.core.records.fromarrays([a1, a2, a3], names='ax,bx,cx')
print(result[0])
print(result[1])
print(result[2])
result.bx

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)


array(['Red', 'Green', 'White', 'Orange'], dtype='<U6')