In [1]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [2]:
random = np.random.random((3,3,3))
random

array([[[0.9572994 , 0.82498547, 0.11775398],
        [0.23776757, 0.15391419, 0.45162253],
        [0.93131819, 0.20488954, 0.90672147]],

       [[0.71559137, 0.91544842, 0.48043405],
        [0.77734348, 0.39633462, 0.99573614],
        [0.15561726, 0.76598007, 0.80024966]],

       [[0.5791592 , 0.71418942, 0.6001427 ],
        [0.62335496, 0.88172028, 0.25624548],
        [0.82116345, 0.12335928, 0.61598286]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
mat = np.diag(np.arange(1, 5), k=-1)

mat

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
x = np.zeros((8,8),dtype=int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [5]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Normalize= (Z-Zmin)/(Zmax-Zmin)
Normalize

array([[0.        , 0.79825259, 0.80302745, 0.4653945 , 0.45528985],
       [0.0450708 , 0.54778357, 0.97652517, 1.        , 0.52806654],
       [0.16139435, 0.11905944, 0.59892854, 0.35579268, 0.70188352],
       [0.83848103, 0.96604517, 0.21421632, 0.25020466, 0.30327676],
       [0.0618548 , 0.15016899, 0.37498841, 0.65152886, 0.01913189]])

# 5.  How to find common values between two arrays?

In [6]:
a1 = [1,2,4,5]
a2 = [1,4,6,7]
intersect = np.intersect1d(a1, a2)
intersect

array([1, 4])

# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
import datetime as dt

today = dt.date.today()
yest = today -  dt.timedelta(days= 1)
tomw = today +  dt.timedelta(days= 1)

print('today', today)
print('yesterday', yest)
print('tomorrow', tomw)

today 2020-07-27
yesterday 2020-07-26
tomorrow 2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [8]:
comp = np.random.randint(1,6, size=(5)) == np.random.randint(1,6, size=(5))
comp.all()

False

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
arr = np.random.randint(3, 100, (10))
print(arr)
maxindex = np.argmax(arr)

arr[maxindex] = 0
print('after change max val = 0')
print(arr)


[81 91  7 62 64  8 95  6 23 92]
after change max val = 0
[81 91  7 62 64  8  0  6 23 92]


# 9. How to print all the values of an array?

In [10]:
arr = np.random.randint(3, 100, (10))
print(*arr)

61 79 19 80 69 67 32 55 34 29


# 10.Subtract the mean of each row of a matrix

In [11]:
print("Original matrix:\n")
np.random.seed(3)
X = np.random.randint(3, 10, (4,4))
print(X)
mean =X.mean(axis=1)
print(mean)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - mean
print(Y)

Original matrix:

[[5 3 4 6]
 [3 3 3 8]
 [8 6 5 6]
 [4 4 5 8]]
[4.5  4.25 6.25 5.25]

Subtract the mean of each row of the said matrix:

[[ 0.5  -1.25 -2.25  0.75]
 [-1.5  -1.25 -3.25  2.75]
 [ 3.5   1.75 -1.25  0.75]
 [-0.5  -0.25 -1.25  2.75]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [12]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)

print(I)
Z += np.bincount(I, minlength=len(Z))
print(Z)


[7 6 0 4 7 8 1 6 2 2 1 3 5 8 1 8 7 8 1 0]
[3. 5. 3. 2. 2. 2. 3. 4. 5. 1.]


# 12.How to get the diagonal of a dot product?

In [13]:
vector_a = np.random.randint(3, 10, (4,4))
vector_b = np.random.randint(3, 10, (4,4))

product = np.dot(vector_a, vector_b) 
print(product)
diag = np.diag(product)

diag

[[152 161 170 203]
 [165 177 184 214]
 [ 91 123 126 138]
 [128 126 134 166]]


array([152, 177, 126, 166])

# 13.How to find the most frequent value in an array?

In [14]:
mostfreq = np.random.randint(0,10,10)
print (mostfreq)

print('rank:', np.bincount(mostfreq).argmax())

[0 0 0 2 2 7 0 5 0 1]
rank: 0


# 14.How to get the n largest values of an array

In [15]:
arr = np.random.randint(3, 100, (10))
print('array')
print(arr)
n = 3
nlargest = arr[(-arr).argsort()[:n]]
print('n-largest')
print(nlargest)

array
[55  5 31 39 93 47 51 62 77 57]
n-largest
[93 77 62]


# 15.How to create a record array from a regular array?

In [16]:
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])

result= np.core.records.fromarrays([a1, a2, a3], names='ax,bx,cx')
print(result[0])
print(result[1])
print(result[2])
result.bx

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)


array(['Red', 'Green', 'White', 'Orange'], dtype='<U6')